### PR TITLE
Some cleanups and documentation updates

### PR DESCRIPTION
**Pull request by orithena**
I got annoyed by the looks of git status, so I started cleaning up...

* Cleaned up git status (by adding more patterns to .gitignore).
* Put index.min.html under version control, since it was the only minified file that is not in git (on that note... do we actually need the minified files under version control?)
* Cleaned prepare_static_ui_sources.py (by adding safeguards against possibly destructive usage).
* Mentioned prepare_static_ui_sources.py in README.

### CODE REVIEW

**Comment by s00500** [comment]
Alright cool,
If you want you can put your script in the Readme before my jsfiddle link, since it is better

Also there is a double no in your help string:
Do not store intermediate minified (but not gzipped) files next to the originals

shouldn't it be:
Do not store intermediate minified files next to the originals (but do generate gzipped files)

?

**Comment by orithena** [comment]
Thanks for pointing that ambiguity out... I meant it as part of the sentence: the intermediate "minified but not gzipped" files.

Your suggestion does not reflect what the script does in that gzipped files are never stored on disk (they're only stored in the C array and saved as part of the header file).

We could leave it as it is (after all, it's only a slightly ambiguous text for an insignificant parameter) ... or I'll recreate that PR :)

**Comment by s00500** [comment]
Ah ok, Hm please change it to something more explicit.
You do not have to recreate a PR, just push into your branch again on your repo aand github will automatically update everything. When your done just let me know

**Comment by orithena** [comment]
... wish I knew about the updatability of PRs sooner... ^^
Okay, there'll be a followup commit somewhen this night (am not home currently).

**Comment by orithena** [comment]
bool pr_is_updated = true;

I also heeded your suggestion regarding the order of the script and the jsfiddle link ... but got a bit carried away and basically rewrote the whole section in the README. Please check before accepting the PR :)

**Comment by s00500** [comment]
Great thank you for your work

**Pull request merged**
