### PR TITLE
Visible/unvisible elements.

### PR DESCRIPTION
**Pull request by Noctr**
You can control the "visibility" property of elements.

### CODE REVIEW

**Comment by s00500** [comment]
Pretty cool, thanks for your contribution!

**Review by s00500 — APPROVED** [review]
If you have the time it would be cool if you could fix the indentation of the ifs...

**Comment by Noctr** [comment]
Thanks for your rating. 
I don't know much about programming (and bad at English, thanks to Google translator). 
In your version of ESPUI, I lacked this functionality and my colleague did the work on the change. 
I just put the modified files on the github and wrote to you. 
I offer you this only as an idea, as it is done in my version, and I ask, if possible, to do this in your version. 

"... If you have the time it would be cool if you could fix the indentation of the ifs ..." 
I don't quite understand what you want. Thanks a lot.

**Comment by s00500** [comment]
Thanks for your contribution!

**Comment by misterm15** [comment]
Hello,
thanks for the add!
How it interact with this visible option?
@Noctr could you share an example?
I would have a usage as the UI has some issues when i have to much buttons so i would disable some when not needed

**Comment by Noctr** [comment]
The project was carried out using the FLProg program (Russian development, allows programming with functional blocks), because of this there is a lot of unnecessary.
See lines 223-226 for what you need.
**Сhange #include <ESPUI-mod.h> to #include <ESPUI.h>**

[ESPUI.zip](https://github.com/s00500/ESPUI/files/7190234/ESPUI.zip)

**Comment by misterm15** [comment]
Thank you!
Tought i also need to change something during the "addcontrol" step of the object...
But it was to simple ;)

Unfortunatley, the updated master files (changed ones for this function) are not working on my side.
Upon loading of the UI in browser the ESP runs into Load Prohibited Error. Seems to try to read a not available address block.
grafik

With control.js , controls.min.js , datacontrolsJS.h and ESPui.h changed to rlase 2.02 files it works.


Thanks and have a good day!

**Pull request merged**
