### PR TITLE
Refactored debug define into DEBUG_ESPUI

### LINKED ISSUE #17: #define debug true messes with async wifimanager
A nice addition to ESPUI is the [ASYNC wifimanager project ](https://github.com/alanswx/ESPAsyncWiFiManager). Sadly fresh out of the box ESPUI and the wifi manager don't compile together because of the way debugging is handled, the "#define debug true" statement in the code. Maybe change it into something better defined and with capitals #define DEBUG_ESPUI or something.

### PR DESCRIPTION
**Pull request by wvdv2002**
This fixes #17

### CODE REVIEW

**Comment by wvdv2002** [comment]
Ah sorry, I just saw that this

**Comment by s00500** [comment]
Can you rebase on master?

**Comment by wvdv2002** [comment]
I can just make a pull request to master instead of development, that would be the easiest?

**Comment by s00500** [comment]
Yeah lets try, open it

**Comment by wvdv2002** [comment]
Ok, I opened it again.

**Comment by wvdv2002** [comment]
Excuse me for the chaos, was a long time ago I did a pull request.

**Comment by s00500** [comment]
Haha alright then, time to get back in shape ;-) Thanks for the additions,  and the formatting in the readme

**Comment by wvdv2002** [comment]
Yeah, probably. Just wanted to help a bit to say thanks for creating this library. It was very useful for two projects I just did. Here are the repositories if you are interested: [ESP-solarfollower](https://github.com/wvdv2002/ESP-solarfollower) and [ESP-shower](https://github.com/wvdv2002/ESP-Shower).

**Pull request merged**
