### PR TITLE
Added a user data parameter to the callbacks to support passing a 'this' pointer for lambda functions

### PR DESCRIPTION
**Pull request by MartinMueller2003**
Existing callbacks have not changed. 100% backwards compatible.
mitigated an occasional crash caused by removing a control.
New parameter is stored in the control structure
Updated addControl to conform to C++ overloading conventions (no preset parms).

### CODE REVIEW

**Comment by iangray001** [comment]
I agree that the use of default parameters was not to my tastes, but I'm going to have to defer to @s00500 on this one. 

Broadly, Lucas, I think this looks fine. I like the idea of a user parameter that can be passed into callback (although I suspect that this is asking for trouble in the hands of the uninitiated...). 

@MartinMueller2003 can you briefly discuss the issue in `removeControl` that you found please?

**Comment by MartinMueller2003** [comment]
> @MartinMueller2003 can you briefly discuss the issue in `removeControl` that you found please?

To be honest, I could not see a problem with the function when reviewing the implementation. However, I was getting periodic crashes when removing large (> 30) numbers of entries. After I rewrote the remove function, the crashes went away. I suspect the real reason for the crashes is an interaction with the Web Server at the same time as the removals. My rewrite changed the timing enough that the crash does not happen. I would suggest adding a semaphore around using the list so that the library becomes a bit more thread safe.

Keep in mind that ESP32 IS multi threaded even if the programmer did not set it up that way.

**Comment by MartinMueller2003** [comment]
Good Day. Any feedback? I have made additional updates to harden the delete functionality but I did not want to mix those changes with this feature.

**Comment by s00500** [comment]
Hey @MartinMueller2003, this looks solid to me thanks for the contribution, having a void pointer as a general user data channel is an established pattern... in the context of this lib I would have argued to use globals for most of the usecases though... after all it depends on the way how the user param is used... one could still hit concurrency issues =D


As for general concurrency related crashes due to the AsyncWebserver: Yes please! everything you can do to make it more stable is highly appreciated! So thanks a lot!

As I mentioned several times here I have not been using this library myself in reccent time a lot, but @iangray001 and some others have done an amazing job in adding features and fixing bugs

Summarizing: I think this PR is a great addition!

**Review by s00500 — APPROVED** [review]

**Comment by MartinMueller2003** [comment]
I use the parm as a this pointer in the callback

      EspuiActiveChoiceListElementId = ESPUI.addControl(
          ControlType::Select,
          Title.c_str(),
          emptyString,
          ControlColor::Turquoise,
          ctrlTab,
          [](Control *sender, int type, void *parm)
          {
             reinterpret_cast<c_ControllerMessages *>(parm)->CbChoiceList(sender, type);
          },
          this);

**Comment by s00500** [comment]
Would you mind adding a couple of lines to the readme explaining the new feature ?

**Comment by MartinMueller2003** [comment]
I have updated the readme file to show an example of using the extended parameter in a lambda function.

**Comment by s00500** [comment]
Awesome, thanks a lot!

**Comment by MartinMueller2003** [comment]
Thanks for reviewing.
Yes it can be an issue and is not much needed in a C implementation but it removes an std:map from my current project since I had to map the id to a this pointer to keep the lambda based callbacks clean in a C++ implementation. There are many callback systems that provide such a parameter.
Martin
    On Sunday, June 12, 2022, 08:50:53 AM EDT, Ian Gray ***@***.***> wrote:  
 
 


I agree that the use of default parameters was not to my tastes, but I'm going to have to defer to @s00500 on this one.

Broadly, Lucas, I think this looks fine. I like the idea of a user parameter that can be passed into callback (although I suspect that this is asking for trouble in the hands of the uninitiated...).

@MartinMueller2003 can you briefly discuss the issue in removeControl that you found please?

**Pull request merged**
