### PR TITLE
Significant restructuring to compensate for small size of WebSocket queues

### PR DESCRIPTION
**Pull request by MartinMueller2003**
Restructured to move from a stateless model to a stateful model allowing ESPUI to support more than WebSocket queue length control updates in a single callback function.

### CODE REVIEW

**Comment by MartinMueller2003** [comment]
OMG: Why a restructuring?

The original implementation assumed a lossless operation. When a callback was made, any control updates were created and queued to the WebSocket layer. Everything was fine until the application needed to generate more changes than the WebSocket egress queue could hold. 

Keep in mind that the ESP code is NOT true multi processing. callbacks are done in the same thread that will eventually send data from the egress queue to the Browser.  That send operation uses polls to empty the egress queue and the poll is blocked by the ESPUI callback processing.

What was done: 

- Made the controls a true class and gave the control class some autonomy to track whether a control had been synchronized or not and marshal the control data as appropriate for transfer to a client.
- Added a per Web Client class that tracks the interactions between application requests and limits the number of messages in the queue going to the websocket via a Finite State Machine.
- Added a per Web Client Finite State Machine to track the type of transfer in progress and isolate actions between clients.
- Modified the add / delete control functionality to use a semaphore in multi-threaded environments and delayed when a control is actually deleted.

Please do a carefull review and I would be happy to set up a conversation to go over the new code structure. At this time the changes are 100% backwards compatible (no timers or poll calls have been added) to existing applications developed using this library. This also fixes a problem in my application where not all fields affected by a change during a callback get updated and you need to manually press the page refresh (internal call to Reload got lost due to queue space)

**Comment by MartinMueller2003** [comment]
Any chance we can have a group review of this where I can do a code walk through? I have been using it for a few weeks now and have not had any issues.

**Comment by thomastech** [comment]
Validation Summary:

I've applied this PR into my radio project. Working, no problems to report.

I'm using Platformio Core 6.1.3, Espressif32 4.4.0, arduinoespressif32 @ 3.20003.220626 (2.0.3). 
Target device is ESP32 TTGO T8 V1.7.1 

I'm currently testing to see if it eliminates the random websocket disconnects. Should be able to report on that soon.

BTW, the PR seems to have been built on the older Arduino LITTLEFS ESP32 Library. The latest is built into arduinoespressif32 and has been renamed to LittleFS (same as ESP8266). So I've changed all ESPUI references of _LITTLEFS_ to _LittleFS_. Plus added _LittleFS @ ^2.0.0_ to lib_deps in my Platformio.ini

- Thomas

**Comment by thomastech** [comment]
Continuing with the validation, I had a browser remain open last night. This morning the Web GUI did not report the dreaded "Disconnect" message, but none of the fields were updating. I found that the controls still worked, but the GUI was not being updated. 

I have never seen this behavior before.

- Thomas

**Comment by MartinMueller2003** [comment]
Are you saying that the PixelLights home page with all of the status indicators was not updating latest data?

**Comment by thomastech** [comment]
More feedback, hope it helps:

I had another occurrence of this oddity. During the test I had two Firefox browsers running on the same WIN10 machine. After about five hours one was still OK, but the other had gone deaf; Control events were working but without any Web GUI updates on the various ESPUI tabs.

- Thomas

**Comment by MartinMueller2003** [comment]
Thanks. Is this using the latest on the pixelradio main line or is it on a different branch?

**Comment by thomastech** [comment]
Current (v1.1.1) main release of PixelRadio, https://github.com/thomastech/PixelRadio
and FireFox is ver 103.0 64-bit.

**Comment by MartinMueller2003** [comment]
> Current (v1.1.1) main release of PixelRadio, https://github.com/thomastech/PixelRadio and FireFox is ver 103.0 64-bit.

The PixelRadio version at that link does not have my latest code. It has a version that is known to have issues with the PixelRadio due to the size of the ESP32 WebSocket queue (delayed me for three weeks figuring out I had not actually been using it wrong). I manually ported the latest ESPUI from my branch into 1.1.1 and have six Chrome browsers and four FireFox browsers all happily updated every 5-8 seconds or so. Yup that is 10 browsers connected at the same time all getting updates at the expected time.

Qyestion: In your testing, did the messages on the serial port continue to come out at the expected rate?

**Comment by thomastech** [comment]
> The PixelRadio version at that link does not have my latest code. 

Sorry for not being clear. The test environment is using PixelRadio V1.1.1 with your PR added to it. This effort is intended to provide validation information on your PR.

This new problem is random and currently I do not know of any conditions that force it to occur. So far I've seen it twice and it took several hours to appear. 

I don't recall the exact conditions in the first occurrence, but in a follow-up test there were two Firefox sessions open; One was monitoring PixelRadio's Home tab and the other was on the Diag tab. After several hours one browser went into the described "deaf" state and the other was still running OK. After a page refresh the bad session was restored to full operation.

- Thomas

**Comment by MartinMueller2003** [comment]
next time it goes deaf, I would like two bits of information: does the usb serial interface still show that updates are being sent and then press f12 and selet console. There you should be seeing the messages coming from the esp. are they present or missing and if present are any errors being reported?

**Comment by MartinMueller2003** [comment]
Just completed a 14 hour run with no dropouts. All 10 browsers are in sync. I need my test setup so I need to stop the test.

**Comment by thomastech** [comment]
I'm running the test, but unfortunately have had to interrupt the hardware several times as I pack up the lab.  If/when the issue occurs I will report what I see from the F12 console. Capturing the serial log won't be possible since the hardware is now too far from my workstation.

I'm preparing for a move and only have a couple days before all my projects will be packed for long term storage. So hopefully I can get some useful info in time.

- Thomas

**Comment by thomastech** [comment]
I captured a "deaf" state. It occurred this morning, a couple hours after I started a new test.

F12 Console Error Message:
```
Uncaught SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
    handleEvent http://pixelradio.local/js/controls.js:10
controls.js:10:361

[Learn more]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/JSON_bad_parse
```

Screenshot:
crash

**Comment by MartinMueller2003** [comment]
That is an excellent catch. I know why things stopped. There is a leading zero in the data stream before the start of the JSON data structure. When the browser parser on the PC crashed, the javascript did not send a retry request to the ESP (that type of recovery action is not in the current javascript code so this is not a surprise). That is an easy fix. The more difficult issue is where did that leading information come from. IF it was the PixelRadio Application it would show up as bad embedded data, not as prepended data. And obviously this is not a normal occurrence for the marshaling function because it did it to only one of the WebSockets, At a minimum I will add some recovery code to the JavaScript to retry the last transaction on parse failure.

**Comment by MartinMueller2003** [comment]
I added code to send a malformed message to the browser. Chrome had no problem ignoring it. Firefox stopped responding because of the unhandled exception. Chrome passed an empty data structure to the transaction handler and we generated a response that resulted in a resend of the data. It looks like the crap is added by the serializejson library function. Not sure how. We will need to modify the javascript to catch the unhandled exception. I will also add code to make sure the json string is really empty before filling it.

**Comment by MartinMueller2003** [comment]
Depending on the error I introduce into the data stream, I can get chrome to stop responding as well.

**Comment by MartinMueller2003** [comment]
Sending this kill both browsers instantly:

"\u0000u{fpp"

**Comment by MartinMueller2003** [comment]
Adding this to the ondata function recovers the browser

    try
    {
      var data = JSON.parse(evt.data);
    }
    catch (Event)
    {
      console.error(Event);
      // start the update over again
      websock.send("uiok:" + 0);
      return;
    }

**Comment by MartinMueller2003** [comment]
Code changes have been integrated and uploaded to my branch. 
@thomastech I tested using PixelRadio and everything seems to be that same as it was. I did verify the workaround is in place and that the string allocation has been updated. You should no longer see the UI hang (at least for that reason).

**Comment by thomastech** [comment]
Thanks for the revised files. I've flashed my hardware and now performing a new validation. Same setup as before, two Firefox browsers and one Edge browser, all on the same PC. I'll let it run for a couple days and then report what I find.

- Thomas

**Comment by thomastech** [comment]
The latest revisions have changed the "deaf" mode behavior. Now the affected browser does a full disconnect and posts the "Error / No Connection" message in the browser's title (css #conStatus field). As before, only one browser is affected at a time. 

Here is the F12 Console from FireFox:

```
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
    handleEvent http://pixelradio.local/js/controls.js:11
    start http://pixelradio.local/js/controls.js:55
    onload http://pixelradio.local/:1
controls.js:13:10

The connection to ws://pixelradio.local/ws was interrupted while the page was loading.
controls.js:9:182

websock Error
controls.js:10:272

error { target: WebSocket, isTrusted: true, srcElement: WebSocket, currentTarget: WebSocket, eventPhase: 2, bubbles: false, cancelable: false, returnValue: true, defaultPrevented: false, composed: false, … }
controls.js:10:301

websock close
controls.js:10:194
```

BTW, I'm building with ArduinoJson 6.19.4. Is that the version you use?

- Thomas

**Comment by MartinMueller2003** [comment]
6.19.4 is what I use as well. I have attached a js file that has a bit more debug output. I dont want to commit it to my main branch. Just unzip and copy it over the version in your ESPUI/src directory.
[dataControlsJS.zip](https://github.com/s00500/ESPUI/files/9275845/dataControlsJS.zip)

Send me the browser console output at a failure.

**Comment by thomastech** [comment]
> Send me the browser console output at a failure.

OK. Now running the tests with the new dataControlsJS.h file.

- Thomas

**Comment by thomastech** [comment]
Three browsers running on the same PC. Two Firefox, one Edge. All three stopped, but at different times. When stopped, all browsers showed the "Error / No Connection" message in the browser's title.

The two Firefox console logs occurred approx 80 mins apart and both had identical messages, including the offending char in the "Raw Data." As follows

```
message { target: WebSocket, isTrusted: true, data: "\u0000u{\"type\":210,\"sliderContinuous\":false,\"startindex\":0,\"totalcontrols\":194,\"controls\":[{\"type\":0,\"label\":\"PixelRadio\"}", origin: "ws://pixelradio.local", lastEventId: "", ports: Restricted, srcElement: WebSocket, currentTarget: WebSocket, eventPhase: 2, bubbles: false, … }
controls.js:10:367

Caught JSON parse error controls.js:13:10
    handleEvent http://pixelradio.local/js/controls.js:13

SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
    handleEvent http://pixelradio.local/js/controls.js:11
controls.js:13:51
    handleEvent http://pixelradio.local/js/controls.js:13

Raw Data: �u{"type":210,"sliderContinuous":false,"startindex":0,"totalcontrols":194,"controls":[{"type":0,"label":"PixelRadio"} 
controls.js:13:72
    handleEvent http://pixelradio.local/js/controls.js:13

start the update over again controls.js:13:109
    handleEvent http://pixelradio.local/js/controls.js:13

The connection to ws://pixelradio.local/ws was interrupted while the page was loading. 
controls.js:9:182
websock Error controls.js:10:272

error { target: WebSocket, isTrusted: true, srcElement: WebSocket, currentTarget: WebSocket, eventPhase: 2, bubbles: false, cancelable: false, returnValue: true, defaultPrevented: false, composed: false, … }
controls.js:10:301

websock close
```

Several hours after the FireFox browsers stopped the Edge Browser stopped. Here is its console log output:

```
WebSocket connection to 'ws://pixelradio.local/ws' failed: Could not decode a text frame as UTF-8.
start @ controls.js:9

controls.js:10 websock Error

controls.js:10 EventisTrusted: truebubbles: falsecancelBubble: falsecancelable: falsecomposed: falsecurrentTarget: WebSocket {url: 'ws://pixelradio.local/ws', readyState: 3, bufferedAmount: 0, onopen: ƒ, onerror: ƒ, …}defaultPrevented: falseeventPhase: 0path: []returnValue: truesrcElement: WebSocket {url: 'ws://pixelradio.local/ws', readyState: 3, bufferedAmount: 0, onopen: ƒ, onerror: ƒ, …}target: WebSocket {url: 'ws://pixelradio.local/ws', readyState: 3, bufferedAmount: 0, onopen: ƒ, onerror: ƒ, …}timeStamp: 29848489.2type: "error"[[Prototype]]: Event

controls.js:10 websock close
```
- Thomas

**Comment by MartinMueller2003** [comment]
Thanks for the data Thomas. 

That actually indicates a problem in lower levels of the stack. About all I can do is make the recovery code more robust. The low level socket library is supposed to convert all information into utf_8 data. That is not something the application is supposed to do yet it would appear as if there is a problem. FYI: On the ESPixelStick project we see similar oddities and have transaction timers in place to repeat requests for data when the connection fails. Looks like I will need to do something similar here.

I will take a few days to think about a good way to recover the connection.

**Comment by thomastech** [comment]
Too bad this requires extra handling to work around a lower level problem. But if the issue is buried deep in a library then that seems to be the most practical solution.

The thing that caught my eye is that the message that has the error is prepended with extra text. To help explain what I mean, here is the message that causes grief:

```
data: "\u0000u{\"type\":210,\"sliderContinuous\":false,\"startindex\":0,\"totalcontrols\":194,\"controls\":[{\"type\":0,\"label\":\"PixelRadio\"}", origin: "ws://pixelradio.local", lastEventId: "", ports: Restricted, srcElement: WebSocket, currentTarget: WebSocket, eventPhase: 2, bubbles: false, … }
```

The leading "\u0000u" (or a similar value) does not appear on valid messages, at least not in the console log.

BTW,  u0000u is the same value you posted on Aug 3 in your example of bad data. So I think you're already aware of this oddity. Or it's just a coincidence.

- Thomas

**Comment by MartinMueller2003** [comment]
I am aware of it. It is an encoded null character. Not sure where the null is coming from. I added test code to my build at the point where I give my message to the WebSocket driver to see if I left one there but it has never triggered. Yet it shows up in the UI.

**Comment by thomastech** [comment]
> It is an encoded null character. Not sure where the null is coming from.

In case it's useful information, the ArduinoJason docs discuss mystery nulls during serialization. A null replaces the data if the memory pool is exceeded.
https://arduinojson.org/v6/issues/document-contains-null-instead-of-string/

I'm using this:
```
ESPUI.jsonUpdateDocumentSize  = 2000; 
ESPUI.jsonInitialDocumentSize = 8000;
``` 

Doubling both values (4000, 16000) does not eliminate the random null. Too bad, would have been fantastic if it was this simple to fix.

But I still have a nagging feeling that ESPUI might be unexpectedly creating something huge that exceeds the JsonDocument's capacity. That might explain the mystery null. 

Along with your other proposed fix that recovers the connection, is there any chance you can add some error handling that reports the memory pool has been exceeded? For troubleshooting all we need is a console log message to say it has occurred.

- Thomas

**Comment by MartinMueller2003** [comment]
Actually I intentionally over fill the document and then bag out the last attempted control, That ensures the messages are as full as possible and transfer in the quickest time. I will dig a bit deeper into cleaning up the null

**Comment by MartinMueller2003** [comment]
I have made all of the changes I plan to make. Can we get this merged into the mainline? I would be happy to schedule an online call to go over the changes I have made.

**Comment by thomastech** [comment]
Any chance you can keep this open until the null data bug is solved? I'm confident that should eliminate the random disconnects.

I wish I had the Websocket experience to fix it. But this bug is past my pay grade. So hopefully you are willing to continue working on it.

BTW, I've completely packed my lab in preparation for a major move. But I will pull my ESP32 project from storage if you need any further testing.

- Thomas

**Comment by MartinMueller2003** [comment]
Since this is a bug in Arduino Json, And I have added code on the browser to detect and report the issue, I am not sure what else I can do.

**Comment by thomastech** [comment]
Sorry, I didn't know the bug is caused by the Json library. 

Weeks ago I had done a lot of searching and came up empty handed; That is to say, there's no prior issue tickets on either the Arduino or Platformio githubs. So I assumed it was a ESPUI lib issue.

Since there's no previous reports about the Websocket disconnects (due to unexpected null data) I suspect there's a coding workaround that avoids it. That could explain why other (non-ESPUI) Arduino projects are not complaining about the problem.

Perhaps wishful thinking, but for sure beyond my skill set to troubleshoot and fix. Now hoping for a kind soul to save the day. :)

- Thomas

**Comment by s00500** [comment]
Hey guys,
This really feels like it has been a pr for long enough ;-)
I have been on holidays for the last 2 and a half weeks and have lots of other work to catch up on as well

@MartinMueller2003 If you wanna have a call were we go through the changes all we can schedule something next week, I think that could be quite nice otherwise I am also ok with merging it as is, based on thomas and your testing so far.

Greetings,
Lukas

**Comment by s00500** [comment]
Hi @MartinMueller2003 why did you close it ?

**Comment by MartinMueller2003** [comment]
There were some merge conflicts with another set of changes that caused me to need to revert my changes, merge the new change and then reapply my changes. I am in the process of testing the reapplied changes and will open a new pull request shortly.

**Comment by MartinMueller2003** [comment]
New PR has been opened. On the plus side, I found a latent bug in the graphpoint handling.
Martin
    On Wednesday, September 21, 2022 at 02:45:12 PM EDT, Lukas Bachschwell ***@***.***> wrote:  
 
 


Hi @MartinMueller2003 why did you close it ?

**Pull request closed without merging**
