### PR TITLE
Proposal: use lambda functions

### PR DESCRIPTION
**Pull request by d-a-v**
(*edited*)

Summary:
- new callback definition allowing lambdas, compatible with legacy regular and extended callbacks
- one new example (copy of complete example) making use of lambda and legacy callback functions
- no API deprecation
- legacy API is preserved
- legacy examples unchanged

Reason:
My intern to whom I haven't been able to refuse anything asked me how to use class methods as callback.
Although README shows how to do that, using lambda functions is more c++.

### CODE REVIEW

**Comment by s00500** [comment]
Hm... I like the idea... is this compatible with all potentially used compilers ? think ol older arduino ide versions and stuff...

@iangray001 @MartinMueller2003 any opinions here ?

**Comment by iangray001** [comment]
Err, so it would raise the minimum C++ standard to C++11, which I presume we probably all at least compile to already. The compilers all support it for the ESP boards so for our targets it should all be fine. 

The original AVR Arduinos won't compile to that so I'm not sure about the default behaviour of the Arduino IDE. 

The only issue might be that it is a bit more complex for people reading the code.

Also this PR has a million other things and changes peppered through it so regarding this change it needs separating out.

**Comment by MartinMueller2003** [comment]
FYI: I prefer lambda functions. I find them much simpler to use

**Comment by MartinMueller2003** [comment]
Always best to keep major changes in a seperate PR. That makes it simpler to verify the change.

**Comment by d-a-v** [comment]
This PR will be simplified when simpler ones get merged.
First is #251

**Comment by d-a-v** [comment]
This PR has been updated, #252 (the last one I hope) is supposed to be merged first.
Please note that [one example has been updated to show how to use lambdas](https://github.com/s00500/ESPUI/pull/249/files#diff-a25fb832f330e10989427fef0c62004e7c2acb6851215ce3c9d93ce0540fa2a0R294-R347).
- Should this be done with the other examples ?
- or Should it be done with only one new example (called like "`LambdaCallbacks.ino`") and leave the other untouched ?

**Comment by croghostrider** [comment]
> > I will try with ESP32 current release.
> 
> Note: Arduino esp32 >= v2.0.0 can compile this PR.

I thin this #254 will fix the problem with the compiler.

**Comment by d-a-v** [comment]
[Changes have been revisited](https://github.com/s00500/ESPUI/pull/249#issue-1883631260).
Apart from a new example, changes are now minimum
(c++11 compatible, usable in IDE, no breaking change, no deprecation).

**Comment by s00500** [comment]
Hey @d-a-v This looks nice, could you resolve the (tiny) conflict ? I think we can merge this after

**Comment by d-a-v** [comment]
Thanks for the heads up, merge is done.

**Pull request merged**
