### PR TITLE
Added tabs and other improvements

### PR DESCRIPTION
**Pull request by eringerli**
# Preface #

I have a project with many controllable settings (20+, in about four categories). Instead of creating my own lib or implement some forms in plain html, I found ESPUI. And it is great: looks good, no hassle with starting and configuring webservers, implementing forms and upload files, automatic synchronisation between clients and definable callbacks (works even with lambdas). But there were some features I missed, so I started to code. I hope, I haven‘t changed too much of it, but to implement the tabs and the drop downs used in my project, there were some pretty invasive changes needed. 

The commits are pretty good commented, so check them out. I haven't changed the README, but added two new demos, one for the new unified API, one for the tabbed view. I changed the existing demo to reflect the change in verbosity of ESPUI, as this can be set through instantiation (in my project, I need the serial line to do other things). Also I added a automatic switchover from client to hotspot, if the wifi-network is not found. That should help newbies to get running faster and use this as a starting point.

# Known Issues #
~~One issue is there though: the pad control isn't shown correctly anymore. As I don't use it (and don't get why it broke, as everything else works perfectly), I think you should look at it.~~
Found it: I set the style of all the `<ul>` and `<li>` in the CSS. It is corrected now (00d996d8ddee4d17cf3ed51dd003db1a58731508) 

# In a nutshell #
* reformated/reindented, minor cleanups
  * added `{}` to all `if`s
* new unified API
  * all the different `Control` are created by `ESPUI::addControl(...)`
  * removed a lot of redundant code (creating `Control` and communication via Websocket)
  * moved a lot of `#defines` to `enums`
  * changed the array of `Control` to a linked list, virtualy limitless amount of elements possible
  * `Control` can have parents
  * check if callbacks exist before calling them
  * some more descriptive error messages
* two new types of `Control`
  * tabs, based on https://github.com/elboletaire/tabbedcontent
  * dropdown lists (`<select>` in html, with `<options>`)
* Gluecode for old API, but callbacks need to be changed (new signature)
* Instantiation of ESPUI has to be in the users app
  * the verbosity of ESPUI can be regulated: from quiet to real talkative
* added default parameters to `ESPUI::begin*(...)`, basic auth is automatically recognised
* moved examples/gui/data/ to data/ and adjusted tools/*.py
* the examples change automatically from wifi client to hotspot

### CODE REVIEW

**Comment by s00500** [comment]
Ok, thanks for the work, this looks really cool
I finally had the time to check it out

There are a few comments that I have though:

- Moving data to top-level directory makes perfect sense, we should update the docs on this though (for manual upload not working anymore with the examples)

- I think the enum ControlColor can still be a anonymous enum, since it makes the code way easier to read and understand, especially if you are getting started (so the type of person this library was originally developed for)

- The Verbosity setting in the constructor: Having a exposed verbosity setting is cool, but I think it does not HAVE to be there. It should be documented but there should be a default value for that. Also I think that the name **VerboseJSON** is kind of confusing, the levels should be Error, info, debug or something.

- As to the NewAPI idea: yes I agree it makes sense to have some generic way of adding controls, but the reason I created these constructors separately was to make it possible to add additional data like min and max for the slider. I think all functions to create controls should still exist like they are now, the parrentControl element (where it is needed) should be the last argument and should have a default so that the Control::noParent value is never needed in the sketch

- And of corse there are quite a few documentation changes still necessary

Apart from that I really like how it looks and works, creating a Control class also makes sense by now, the tab plugin seems nice and small, and it is a really cool feature

So I think steps now would be cleaning up and addressing these issue

**Comment by eringerli** [comment]
Thanks for the review.

* As I have never worked with ESPs before, I wasn't aware of manual uploading.
* I personally don't like poluting the global namespace or using `#defines` for values, so I explicitely made them non-anonymous. And C++ is strongly typed, so there are many compile errors catched by explicitely add `ControlColor::`. In my opinion, doing so makes it also easier to read, but that is your desicion.
* I thought so too, but I was doing work on other projects, so I forgot about it. 
* Yeah, as I used `addControl` directly in my project, I didn't want to change the signature of the other methods, to keep it compatible.
* Documenting all the changes makes sense, but I didn't wanted to change it before the changes are final and reviewed.

How about to bump a major version number? And I think I found a solution for the `min` and `max` for the slider: add two `Control` with new types as children to the slider. That makes them updatable too.

**Comment by s00500** [comment]
Ok, I pushed your work to a 2.0.0 Branch and will makes some changes on there, feel free to comment, This has som really great improvements but I will also still make some changes, also I want to add support for the new version of Arduino JSON to 2.0.0 and build in some of the open issues

**Comment by eringerli** [comment]
Thanks, as I don't have time to spare (ESPUI is just a part amongst many in my project), I push changes as I make them.

I removed the dependency for unique labels (and addressing the elements with labels). For in my project, I have to configure many GPIOs for different things, these have the same labels (obviously, as I add them with a helper function). Currently, I have around 260 elements in the linked list.

I have updated the slider, but didn't style it much. But now it is possible, to add a min, max and step value to numbers and sliders. I hadn't have time to document it, but you basicaly add an element with the type and the numner/slider as parent (you can look in my "esp32-aog"-repository, in the file src/main.cpp)

**Comment by s00500** [comment]
Closing since it has been added to 2.0 branch already, thanks for the contributions, I will try to push the release soon :-)

**Pull request closed without merging**
