### PR TITLE
Reduce HEAP usage

### PR DESCRIPTION
**Pull request by enwi**
Reduce the HEAP (RAM) usage by using `const String&` for functions and moving constant Strings into PROGMEM (Flash) by using `F()`, `PSTR()` and `printf_P`.

This reduces the HEAP usage for the `tabbedGui` example from 31988 bytes to 31164 bytes in other words by 824 bytes.

### CODE REVIEW

**Comment by enwi** [comment]
Another option might be to be able to remove all debugging code with a preprocessor directive `#define DEBUG`

**Comment by s00500** [comment]
Nice, thanks, it should be noted though that on the ESP32 this will likely make no difference as it stores const strings in flash automatically, or did I miss something ? For the ESP8266 it is a nice improvement though! I would argue against stripping out debug using a define in the context of this library, as this makes debugging a little more complicated

**Comment by enwi** [comment]
I don't know for the ESP32, but sometimes you can't trust the compiler.

I have a proposal for the preprocessor directive. You could make it that it is defaulted to be defined and pro users that know what they are doing could undefine it and use more IROM.

**Comment by s00500** [comment]
Your proposal sounds good, if you want to add it you could do so on this PR, otherwise I think we can just merge it, so let me know :-)

**Comment by enwi** [comment]
I will add the defines and also check what difference it will make.

**Comment by enwi** [comment]
Removing the define 'DEBUG_ESPUI' reduces the Flash as well as the HEAP (RAM) usage even further.

HEAP (RAM) is reduced from 31164 bytes (with earlier optimizations) to 31124 bytes by 40 bytes.
Flash is reduced from 379644 bytes (with earlier optimizations) to 372700 bytes by 6944 bytes.

**Comment by enwi** [comment]
To also get a better overview of what is happening here are all outputs of Arduino IDE compared with target ESP8266:

Without any optimizations:
```
IROM   : 340196          - code in flash         (default or ICACHE_FLASH_ATTR) 
IRAM   : 27424   / 32768 - code in IRAM          (ICACHE_RAM_ATTR, ISRs...) 
DATA   : 1372  )         - initialized variables (global, static) in RAM/HEAP 
RODATA : 5016  ) / 81920 - constants             (global, static) in RAM/HEAP 
BSS    : 25600 )         - zeroed variables      (global, static) in RAM/HEAP 
```

Use const String& where possible:
```
IROM   : 340164          - code in flash         (default or ICACHE_FLASH_ATTR) 
IRAM   : 27424   / 32768 - code in IRAM          (ICACHE_RAM_ATTR, ISRs...) 
DATA   : 1372  )         - initialized variables (global, static) in RAM/HEAP 
RODATA : 5016  ) / 81920 - constants             (global, static) in RAM/HEAP 
BSS    : 25600 )         - zeroed variables      (global, static) in RAM/HEAP
```

Use F() and PSTR():
```
IROM   : 346588          - code in flash         (default or ICACHE_FLASH_ATTR) 
IRAM   : 27508   / 32768 - code in IRAM          (ICACHE_RAM_ATTR, ISRs...) 
DATA   : 1388  )         - initialized variables (global, static) in RAM/HEAP 
RODATA : 4160  ) / 81920 - constants             (global, static) in RAM/HEAP 
BSS    : 25616 )         - zeroed variables      (global, static) in RAM/HEAP 
```

Remove debug code completely:
```
IROM   : 339760          - code in flash         (default or ICACHE_FLASH_ATTR) 
IRAM   : 27424   / 32768 - code in IRAM          (ICACHE_RAM_ATTR, ISRs...) 
DATA   : 1372  )         - initialized variables (global, static) in RAM/HEAP 
RODATA : 4144  ) / 81920 - constants             (global, static) in RAM/HEAP 
BSS    : 25608 )         - zeroed variables      (global, static) in RAM/HEAP 
```

**Comment by s00500** [comment]
ok cool, thanks for the nice results =D could you rebase on master and also include #define DEBUG_ESPUI per default ?

**Comment by enwi** [comment]
[`#define DEBUG_ESPUI true`](url) is already present inside your code base.

**Comment by enwi** [comment]
@s00500 Rebase is pushed

**Comment by s00500** [comment]
Sweet, thanks for your work =D

**Pull request merged**
