### PR TITLE
Add remControl() method for remove contols

### PR DESCRIPTION
**Pull request by nen777w**

### CODE REVIEW

**Comment by s00500** [comment]
Very nice, thanks for the PR!

Could you please reset the changes of 
data/js/graph.min.js 
data/js/....
and
src/data....h
...

back to their original state ? as you did not modify their sources there is no need to regenerate them

The only files that need to be commited in their regenerated state are 
data/js/controls.min.js 
 src/dataControlsJS.h 

:-)

**Comment by s00500** [comment]
Actually I also do not think it is necessary to do a full window reload ... I will try to look into this quickly...

**Comment by s00500** [comment]
Oh, it is not necessary to close and reopen a pull request, just make commits on your branch and push them, then they will show up here ;-)

**Comment by nen777w** [comment]
> Oh, it is not necessary to close and reopen a pull request, just make commits on your branch and push them, then they will show up here ;-)

Yah, I know, but I made several mistakes when try to updating my commits last time, then an I push it on GH, then reverting it... then I decide just create new pull request instead of trying to fix it.
Sorry :-)

**Comment by s00500** [comment]
Ok, can ou try out the changes I did on https://github.com/s00500/ESPUI/tree/add_method_for_remove_controls ?
I removed the redundant reload functions, and also made sure calling jsonDom alone should resend state to all the clients and properly rebuild the dom. This should at least save some trouble, as the server does not suddenly need to serve all static files again when several clients would reload...

**Pull request closed without merging**
