### PR TITLE
One bugfix, one small feature

### PR DESCRIPTION
**Pull request by iangray001**
Two small updates. One allows Button text to be updated dynamically. The other fixes a silly bug on my part relating to multiple clients being connected at the same time.

### CODE REVIEW

**Comment by iangray001** [comment]
@thomastech this should fix your repeating control problem

**Comment by thomastech** [comment]
@iangray001 Tested PR, repeating control problem fixed. Thank you!

- Thomas

**Review by s00500 — APPROVED** [review]
Awesome work!!!

**Comment by s00500** [comment]
@iangray001 just let me know if you think a new release would be due...

**Comment by iangray001** [comment]
Not quite. I should package up and test the bits I'm currently doing (Time, Vertical Controls), and then update the documentation. Then maybe we can bump the version.

**Pull request merged**
